//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DETicketReader {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DETicketReader.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA2QpgREDTsrDAyO57yEAz
        ///W3YYKYVnzFlS2OZO4sw1bAa73JGidioLkp4Y/s1PZ7kopm+x1RD40UT7x/9+bZWg
        ///DDuO4Nph5opbJkZIS/83qxNzP2axnlrkf8b8iRYdHr+Ul0nNhlax4EwAWK1SgXtL
        ///eGuhpV1rJD+pMomPfkh/gpHcxDBfujJH3bbCr536XAROyDv8Qww20JfjtnoTGkWH
        ///dgM2GRn6XoDvnd3YSEZpL2nUNIT20+c9MjbwaCcJ93VFpeIMTCXVbvKre/Se45Fa
        ///k2zOaTyfdC40fgdf93UrVR475EN4FHMMgFVQmZPbGTjirIlVxRcSdk5pTVRqrlsF
        ////A9fhtdOPUCoSXXHClf9V3Ef1sSlzhVAReVAX3GGwRt2Tq8HrOMq+o9Fgxgl1WC3
        ///NbHUI2x3EmyPID1PKbXLw4tpNjngDotCG96QsdC85zF6C9H5yO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CACertificate {
            get {
                return ResourceManager.GetString("CACertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9E 81 80 70 21 AA 6C BE 2C 07 3A 37 FE 43 83 EF 08 F5 12 14 2F C8 AD 8D 72 24 5F C8 64 B2 AF 5D 17 A6 34 7F 90 6C 13 94 AC 4B 7D 7A 66 46 70 D2 EA F7 ED E0 19 9C 07 E8 A2 71 C4 CD 5A 44 01 A8 EC 83 FC E1 A2 F2 51 0F D8 A0 39 BE CB BA 7C F5 73 56 9E 1D A4 B8 68 73 25 12 05 F7 A4 4C E4 6D 9C 59 19 02 9E EC AE 1A 39 BC E4 05 19 6B 03 99 96 C5 2A CE 17 FD 60 72 96 8F 7F 28 A8 78 59 EA 18 05 CF 9A 0F 00 00 00 00 00 00 00 00 00 00 56 44 56 11 09 7F 21 81 C8 5F 37 81 C0 39 F2 C0 04 92 04 5A F1 51 8A 57 C5 D7 73 43 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputData {
            get {
                return ResourceManager.GetString("InputData", resourceCulture);
            }
        }
    }
}
